runtime: python310

entrypoint: gunicorn -w 1 -k uvicorn.workers.UvicornWorker app.shared.infra.http.main:app

instance_class: F1

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto